/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.1.112 */
/* Module Version: 5.7 */
/* Sat Mar 31 18:15:05 2018 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ), .LOCK( ));
