/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.2.115 */
/* Module Version: 5.7 */
/* Thu Jul 04 17:14:59 2019 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ), .LOCK( ));
