/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 5.1 */
/* Sun Mar  4 14:38:33 2018 */

/* parameterized module instance */
fifo_16 __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), .Q( ), 
    .Empty( ), .Full( ), .AlmostEmpty( ), .AlmostFull( ));
