/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.2.115 */
/* Module Version: 5.8 */
/* Thu May 30 17:11:18 2019 */

/* parameterized module instance */
fifo_16bit __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), .AlmostEmpty( ), 
    .AlmostFull( ));
