/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.10.2.115 */
/* Module Version: 5.8 */
/* D:\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n fifo_8bit_buffer -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type ebfifo -depth 4096 -width 8 -rwidth 8 -reset_rel SYNC -pe -1 -pf 2048 -pf2 2000 -fdc D:/Work/nut2nt-lattice/nuts2_framer/FIFO_buffer/fifo_8bit_buffer/fifo_8bit_buffer.fdc  */
/* Thu Jul 04 19:19:43 2019 */


`timescale 1 ns / 1 ps
module fifo_8bit_buffer (Data, WrClock, RdClock, WrEn, RdEn, Reset, 
    RPReset, Q, Empty, Full, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [7:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [7:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostFull;

    wire invout_1;
    wire invout_0;
    wire w_g2b_xor_cluster_2_1;
    wire w_g2b_xor_cluster_2;
    wire w_g2b_xor_cluster_1;
    wire r_g2b_xor_cluster_2_1;
    wire r_g2b_xor_cluster_2;
    wire r_g2b_xor_cluster_1;
    wire w_gdata_0;
    wire w_gdata_1;
    wire w_gdata_2;
    wire w_gdata_3;
    wire w_gdata_4;
    wire w_gdata_5;
    wire w_gdata_6;
    wire w_gdata_7;
    wire w_gdata_8;
    wire w_gdata_9;
    wire w_gdata_10;
    wire w_gdata_11;
    wire wptr_0;
    wire wptr_1;
    wire wptr_2;
    wire wptr_3;
    wire wptr_4;
    wire wptr_5;
    wire wptr_6;
    wire wptr_7;
    wire wptr_8;
    wire wptr_9;
    wire wptr_10;
    wire wptr_11;
    wire wptr_12;
    wire r_gdata_0;
    wire r_gdata_1;
    wire r_gdata_2;
    wire r_gdata_3;
    wire r_gdata_4;
    wire r_gdata_5;
    wire r_gdata_6;
    wire r_gdata_7;
    wire r_gdata_8;
    wire r_gdata_9;
    wire r_gdata_10;
    wire r_gdata_11;
    wire rptr_0;
    wire rptr_1;
    wire rptr_2;
    wire rptr_3;
    wire rptr_4;
    wire rptr_5;
    wire rptr_6;
    wire rptr_7;
    wire rptr_8;
    wire rptr_9;
    wire rptr_10;
    wire rptr_11;
    wire rptr_12;
    wire w_gcount_0;
    wire w_gcount_1;
    wire w_gcount_2;
    wire w_gcount_3;
    wire w_gcount_4;
    wire w_gcount_5;
    wire w_gcount_6;
    wire w_gcount_7;
    wire w_gcount_8;
    wire w_gcount_9;
    wire w_gcount_10;
    wire w_gcount_11;
    wire w_gcount_12;
    wire r_gcount_0;
    wire r_gcount_1;
    wire r_gcount_2;
    wire r_gcount_3;
    wire r_gcount_4;
    wire r_gcount_5;
    wire r_gcount_6;
    wire r_gcount_7;
    wire r_gcount_8;
    wire r_gcount_9;
    wire r_gcount_10;
    wire r_gcount_11;
    wire r_gcount_12;
    wire w_gcount_r20;
    wire w_gcount_r0;
    wire w_gcount_r21;
    wire w_gcount_r1;
    wire w_gcount_r22;
    wire w_gcount_r2;
    wire w_gcount_r23;
    wire w_gcount_r3;
    wire w_gcount_r24;
    wire w_gcount_r4;
    wire w_gcount_r25;
    wire w_gcount_r5;
    wire w_gcount_r26;
    wire w_gcount_r6;
    wire w_gcount_r27;
    wire w_gcount_r7;
    wire w_gcount_r28;
    wire w_gcount_r8;
    wire w_gcount_r29;
    wire w_gcount_r9;
    wire w_gcount_r210;
    wire w_gcount_r10;
    wire w_gcount_r211;
    wire w_gcount_r11;
    wire w_gcount_r212;
    wire w_gcount_r12;
    wire r_gcount_w20;
    wire r_gcount_w0;
    wire r_gcount_w21;
    wire r_gcount_w1;
    wire r_gcount_w22;
    wire r_gcount_w2;
    wire r_gcount_w23;
    wire r_gcount_w3;
    wire r_gcount_w24;
    wire r_gcount_w4;
    wire r_gcount_w25;
    wire r_gcount_w5;
    wire r_gcount_w26;
    wire r_gcount_w6;
    wire r_gcount_w27;
    wire r_gcount_w7;
    wire r_gcount_w28;
    wire r_gcount_w8;
    wire r_gcount_w29;
    wire r_gcount_w9;
    wire r_gcount_w210;
    wire r_gcount_w10;
    wire r_gcount_w211;
    wire r_gcount_w11;
    wire r_gcount_w212;
    wire r_gcount_w12;
    wire empty_i;
    wire rRst;
    wire full_i;
    wire af;
    wire af_d;
    wire iwcount_0;
    wire iwcount_1;
    wire w_gctr_ci;
    wire iwcount_2;
    wire iwcount_3;
    wire co0;
    wire iwcount_4;
    wire iwcount_5;
    wire co1;
    wire iwcount_6;
    wire iwcount_7;
    wire co2;
    wire iwcount_8;
    wire iwcount_9;
    wire co3;
    wire iwcount_10;
    wire iwcount_11;
    wire co4;
    wire iwcount_12;
    wire co6;
    wire co5;
    wire wcount_12;
    wire ircount_0;
    wire ircount_1;
    wire r_gctr_ci;
    wire ircount_2;
    wire ircount_3;
    wire co0_1;
    wire ircount_4;
    wire ircount_5;
    wire co1_1;
    wire ircount_6;
    wire ircount_7;
    wire co2_1;
    wire ircount_8;
    wire ircount_9;
    wire co3_1;
    wire ircount_10;
    wire ircount_11;
    wire co4_1;
    wire ircount_12;
    wire co6_1;
    wire co5_1;
    wire rcount_12;
    wire rden_i;
    wire cmp_ci;
    wire wcount_r0;
    wire wcount_r1;
    wire rcount_0;
    wire rcount_1;
    wire co0_2;
    wire wcount_r2;
    wire wcount_r3;
    wire rcount_2;
    wire rcount_3;
    wire co1_2;
    wire wcount_r4;
    wire wcount_r5;
    wire rcount_4;
    wire rcount_5;
    wire co2_2;
    wire wcount_r6;
    wire wcount_r7;
    wire rcount_6;
    wire rcount_7;
    wire co3_2;
    wire wcount_r8;
    wire w_g2b_xor_cluster_0;
    wire rcount_8;
    wire rcount_9;
    wire co4_2;
    wire wcount_r10;
    wire wcount_r11;
    wire rcount_10;
    wire rcount_11;
    wire co5_2;
    wire empty_cmp_clr;
    wire empty_cmp_set;
    wire empty_d;
    wire empty_d_c;
    wire cmp_ci_1;
    wire wcount_0;
    wire wcount_1;
    wire co0_3;
    wire wcount_2;
    wire wcount_3;
    wire co1_3;
    wire wcount_4;
    wire wcount_5;
    wire co2_3;
    wire wcount_6;
    wire wcount_7;
    wire co3_3;
    wire wcount_8;
    wire wcount_9;
    wire co4_3;
    wire wcount_10;
    wire wcount_11;
    wire co5_3;
    wire full_cmp_clr;
    wire full_cmp_set;
    wire full_d;
    wire full_d_c;
    wire iaf_setcount_0;
    wire iaf_setcount_1;
    wire af_set_ctr_ci;
    wire iaf_setcount_2;
    wire iaf_setcount_3;
    wire co0_4;
    wire iaf_setcount_4;
    wire iaf_setcount_5;
    wire co1_4;
    wire iaf_setcount_6;
    wire iaf_setcount_7;
    wire co2_4;
    wire iaf_setcount_8;
    wire iaf_setcount_9;
    wire co3_4;
    wire iaf_setcount_10;
    wire iaf_setcount_11;
    wire co4_4;
    wire iaf_setcount_12;
    wire co6_2;
    wire co5_4;
    wire af_setcount_12;
    wire cmp_ci_2;
    wire af_setcount_0;
    wire af_setcount_1;
    wire co0_5;
    wire af_setcount_2;
    wire af_setcount_3;
    wire co1_5;
    wire af_setcount_4;
    wire af_setcount_5;
    wire co2_5;
    wire af_setcount_6;
    wire af_setcount_7;
    wire co3_5;
    wire af_setcount_8;
    wire af_setcount_9;
    wire co4_5;
    wire af_setcount_10;
    wire af_setcount_11;
    wire co5_5;
    wire af_set_cmp_clr;
    wire af_set_cmp_set;
    wire af_set;
    wire af_set_c;
    wire iaf_clrcount_0;
    wire iaf_clrcount_1;
    wire af_clr_ctr_ci;
    wire iaf_clrcount_2;
    wire iaf_clrcount_3;
    wire co0_6;
    wire iaf_clrcount_4;
    wire iaf_clrcount_5;
    wire co1_6;
    wire iaf_clrcount_6;
    wire iaf_clrcount_7;
    wire co2_6;
    wire iaf_clrcount_8;
    wire iaf_clrcount_9;
    wire co3_6;
    wire iaf_clrcount_10;
    wire iaf_clrcount_11;
    wire co4_6;
    wire iaf_clrcount_12;
    wire co6_3;
    wire co5_6;
    wire af_clrcount_12;
    wire wren_i;
    wire cmp_ci_3;
    wire rcount_w0;
    wire rcount_w1;
    wire af_clrcount_0;
    wire af_clrcount_1;
    wire co0_7;
    wire rcount_w2;
    wire rcount_w3;
    wire af_clrcount_2;
    wire af_clrcount_3;
    wire co1_7;
    wire rcount_w4;
    wire rcount_w5;
    wire af_clrcount_4;
    wire af_clrcount_5;
    wire co2_7;
    wire rcount_w6;
    wire rcount_w7;
    wire af_clrcount_6;
    wire af_clrcount_7;
    wire co3_7;
    wire rcount_w8;
    wire r_g2b_xor_cluster_0;
    wire af_clrcount_8;
    wire af_clrcount_9;
    wire co4_7;
    wire rcount_w10;
    wire rcount_w11;
    wire af_clrcount_10;
    wire af_clrcount_11;
    wire co5_7;
    wire af_clr_cmp_clr;
    wire af_clr_cmp_set;
    wire af_clr;
    wire scuba_vhi;
    wire scuba_vlo;
    wire af_clr_c;

    AND2 AND2_t26 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_1 (.A(full_i), .Z(invout_1));

    AND2 AND2_t25 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_0 (.A(empty_i), .Z(invout_0));

    OR2 OR2_t24 (.A(Reset), .B(RPReset), .Z(rRst));

    XOR2 XOR2_t23 (.A(wcount_0), .B(wcount_1), .Z(w_gdata_0));

    XOR2 XOR2_t22 (.A(wcount_1), .B(wcount_2), .Z(w_gdata_1));

    XOR2 XOR2_t21 (.A(wcount_2), .B(wcount_3), .Z(w_gdata_2));

    XOR2 XOR2_t20 (.A(wcount_3), .B(wcount_4), .Z(w_gdata_3));

    XOR2 XOR2_t19 (.A(wcount_4), .B(wcount_5), .Z(w_gdata_4));

    XOR2 XOR2_t18 (.A(wcount_5), .B(wcount_6), .Z(w_gdata_5));

    XOR2 XOR2_t17 (.A(wcount_6), .B(wcount_7), .Z(w_gdata_6));

    XOR2 XOR2_t16 (.A(wcount_7), .B(wcount_8), .Z(w_gdata_7));

    XOR2 XOR2_t15 (.A(wcount_8), .B(wcount_9), .Z(w_gdata_8));

    XOR2 XOR2_t14 (.A(wcount_9), .B(wcount_10), .Z(w_gdata_9));

    XOR2 XOR2_t13 (.A(wcount_10), .B(wcount_11), .Z(w_gdata_10));

    XOR2 XOR2_t12 (.A(wcount_11), .B(wcount_12), .Z(w_gdata_11));

    XOR2 XOR2_t11 (.A(rcount_0), .B(rcount_1), .Z(r_gdata_0));

    XOR2 XOR2_t10 (.A(rcount_1), .B(rcount_2), .Z(r_gdata_1));

    XOR2 XOR2_t9 (.A(rcount_2), .B(rcount_3), .Z(r_gdata_2));

    XOR2 XOR2_t8 (.A(rcount_3), .B(rcount_4), .Z(r_gdata_3));

    XOR2 XOR2_t7 (.A(rcount_4), .B(rcount_5), .Z(r_gdata_4));

    XOR2 XOR2_t6 (.A(rcount_5), .B(rcount_6), .Z(r_gdata_5));

    XOR2 XOR2_t5 (.A(rcount_6), .B(rcount_7), .Z(r_gdata_6));

    XOR2 XOR2_t4 (.A(rcount_7), .B(rcount_8), .Z(r_gdata_7));

    XOR2 XOR2_t3 (.A(rcount_8), .B(rcount_9), .Z(r_gdata_8));

    XOR2 XOR2_t2 (.A(rcount_9), .B(rcount_10), .Z(r_gdata_9));

    XOR2 XOR2_t1 (.A(rcount_10), .B(rcount_11), .Z(r_gdata_10));

    XOR2 XOR2_t0 (.A(rcount_11), .B(rcount_12), .Z(r_gdata_11));

    defparam LUT4_38.initval =  16'h6996 ;
    ROM16X1A LUT4_38 (.AD3(w_gcount_r29), .AD2(w_gcount_r210), .AD1(w_gcount_r211), 
        .AD0(w_gcount_r212), .DO0(w_g2b_xor_cluster_0));

    defparam LUT4_37.initval =  16'h6996 ;
    ROM16X1A LUT4_37 (.AD3(w_gcount_r25), .AD2(w_gcount_r26), .AD1(w_gcount_r27), 
        .AD0(w_gcount_r28), .DO0(w_g2b_xor_cluster_1));

    defparam LUT4_36.initval =  16'h6996 ;
    ROM16X1A LUT4_36 (.AD3(w_gcount_r21), .AD2(w_gcount_r22), .AD1(w_gcount_r23), 
        .AD0(w_gcount_r24), .DO0(w_g2b_xor_cluster_2));

    defparam LUT4_35.initval =  16'h6996 ;
    ROM16X1A LUT4_35 (.AD3(w_gcount_r211), .AD2(w_gcount_r212), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(wcount_r11));

    defparam LUT4_34.initval =  16'h6996 ;
    ROM16X1A LUT4_34 (.AD3(w_gcount_r210), .AD2(w_gcount_r211), .AD1(w_gcount_r212), 
        .AD0(scuba_vlo), .DO0(wcount_r10));

    defparam LUT4_33.initval =  16'h6996 ;
    ROM16X1A LUT4_33 (.AD3(w_gcount_r28), .AD2(w_gcount_r29), .AD1(w_gcount_r210), 
        .AD0(wcount_r11), .DO0(wcount_r8));

    defparam LUT4_32.initval =  16'h6996 ;
    ROM16X1A LUT4_32 (.AD3(w_gcount_r27), .AD2(w_gcount_r28), .AD1(w_gcount_r29), 
        .AD0(wcount_r10), .DO0(wcount_r7));

    defparam LUT4_31.initval =  16'h6996 ;
    ROM16X1A LUT4_31 (.AD3(w_gcount_r26), .AD2(w_gcount_r27), .AD1(w_gcount_r28), 
        .AD0(w_g2b_xor_cluster_0), .DO0(wcount_r6));

    defparam LUT4_30.initval =  16'h6996 ;
    ROM16X1A LUT4_30 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(wcount_r5));

    defparam LUT4_29.initval =  16'h6996 ;
    ROM16X1A LUT4_29 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_gcount_r24), .AD0(scuba_vlo), .DO0(wcount_r4));

    defparam LUT4_28.initval =  16'h6996 ;
    ROM16X1A LUT4_28 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_gcount_r23), .AD0(w_gcount_r24), .DO0(wcount_r3));

    defparam LUT4_27.initval =  16'h6996 ;
    ROM16X1A LUT4_27 (.AD3(w_gcount_r22), .AD2(w_gcount_r23), .AD1(w_gcount_r24), 
        .AD0(scuba_vlo), .DO0(w_g2b_xor_cluster_2_1));

    defparam LUT4_26.initval =  16'h6996 ;
    ROM16X1A LUT4_26 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_g2b_xor_cluster_2_1), .AD0(scuba_vlo), .DO0(wcount_r2));

    defparam LUT4_25.initval =  16'h6996 ;
    ROM16X1A LUT4_25 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_g2b_xor_cluster_2), .AD0(scuba_vlo), .DO0(wcount_r1));

    defparam LUT4_24.initval =  16'h6996 ;
    ROM16X1A LUT4_24 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_g2b_xor_cluster_2), .AD0(w_gcount_r20), .DO0(wcount_r0));

    defparam LUT4_23.initval =  16'h6996 ;
    ROM16X1A LUT4_23 (.AD3(r_gcount_w29), .AD2(r_gcount_w210), .AD1(r_gcount_w211), 
        .AD0(r_gcount_w212), .DO0(r_g2b_xor_cluster_0));

    defparam LUT4_22.initval =  16'h6996 ;
    ROM16X1A LUT4_22 (.AD3(r_gcount_w25), .AD2(r_gcount_w26), .AD1(r_gcount_w27), 
        .AD0(r_gcount_w28), .DO0(r_g2b_xor_cluster_1));

    defparam LUT4_21.initval =  16'h6996 ;
    ROM16X1A LUT4_21 (.AD3(r_gcount_w21), .AD2(r_gcount_w22), .AD1(r_gcount_w23), 
        .AD0(r_gcount_w24), .DO0(r_g2b_xor_cluster_2));

    defparam LUT4_20.initval =  16'h6996 ;
    ROM16X1A LUT4_20 (.AD3(r_gcount_w211), .AD2(r_gcount_w212), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(rcount_w11));

    defparam LUT4_19.initval =  16'h6996 ;
    ROM16X1A LUT4_19 (.AD3(r_gcount_w210), .AD2(r_gcount_w211), .AD1(r_gcount_w212), 
        .AD0(scuba_vlo), .DO0(rcount_w10));

    defparam LUT4_18.initval =  16'h6996 ;
    ROM16X1A LUT4_18 (.AD3(r_gcount_w28), .AD2(r_gcount_w29), .AD1(r_gcount_w210), 
        .AD0(rcount_w11), .DO0(rcount_w8));

    defparam LUT4_17.initval =  16'h6996 ;
    ROM16X1A LUT4_17 (.AD3(r_gcount_w27), .AD2(r_gcount_w28), .AD1(r_gcount_w29), 
        .AD0(rcount_w10), .DO0(rcount_w7));

    defparam LUT4_16.initval =  16'h6996 ;
    ROM16X1A LUT4_16 (.AD3(r_gcount_w26), .AD2(r_gcount_w27), .AD1(r_gcount_w28), 
        .AD0(r_g2b_xor_cluster_0), .DO0(rcount_w6));

    defparam LUT4_15.initval =  16'h6996 ;
    ROM16X1A LUT4_15 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(rcount_w5));

    defparam LUT4_14.initval =  16'h6996 ;
    ROM16X1A LUT4_14 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_gcount_w24), .AD0(scuba_vlo), .DO0(rcount_w4));

    defparam LUT4_13.initval =  16'h6996 ;
    ROM16X1A LUT4_13 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_gcount_w23), .AD0(r_gcount_w24), .DO0(rcount_w3));

    defparam LUT4_12.initval =  16'h6996 ;
    ROM16X1A LUT4_12 (.AD3(r_gcount_w22), .AD2(r_gcount_w23), .AD1(r_gcount_w24), 
        .AD0(scuba_vlo), .DO0(r_g2b_xor_cluster_2_1));

    defparam LUT4_11.initval =  16'h6996 ;
    ROM16X1A LUT4_11 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_g2b_xor_cluster_2_1), .AD0(scuba_vlo), .DO0(rcount_w2));

    defparam LUT4_10.initval =  16'h6996 ;
    ROM16X1A LUT4_10 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_g2b_xor_cluster_2), .AD0(scuba_vlo), .DO0(rcount_w1));

    defparam LUT4_9.initval =  16'h6996 ;
    ROM16X1A LUT4_9 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_g2b_xor_cluster_2), .AD0(r_gcount_w20), .DO0(rcount_w0));

    defparam LUT4_8.initval =  16'h0410 ;
    ROM16X1A LUT4_8 (.AD3(rptr_12), .AD2(rcount_12), .AD1(w_gcount_r212), 
        .AD0(scuba_vlo), .DO0(empty_cmp_set));

    defparam LUT4_7.initval =  16'h1004 ;
    ROM16X1A LUT4_7 (.AD3(rptr_12), .AD2(rcount_12), .AD1(w_gcount_r212), 
        .AD0(scuba_vlo), .DO0(empty_cmp_clr));

    defparam LUT4_6.initval =  16'h0140 ;
    ROM16X1A LUT4_6 (.AD3(wptr_12), .AD2(wcount_12), .AD1(r_gcount_w212), 
        .AD0(scuba_vlo), .DO0(full_cmp_set));

    defparam LUT4_5.initval =  16'h4001 ;
    ROM16X1A LUT4_5 (.AD3(wptr_12), .AD2(wcount_12), .AD1(r_gcount_w212), 
        .AD0(scuba_vlo), .DO0(full_cmp_clr));

    defparam LUT4_4.initval =  16'h4c32 ;
    ROM16X1A LUT4_4 (.AD3(af_setcount_12), .AD2(wcount_12), .AD1(r_gcount_w212), 
        .AD0(wptr_12), .DO0(af_set_cmp_set));

    defparam LUT4_3.initval =  16'h8001 ;
    ROM16X1A LUT4_3 (.AD3(af_setcount_12), .AD2(wcount_12), .AD1(r_gcount_w212), 
        .AD0(wptr_12), .DO0(af_set_cmp_clr));

    defparam LUT4_2.initval =  16'h4c32 ;
    ROM16X1A LUT4_2 (.AD3(af_clrcount_12), .AD2(wcount_12), .AD1(r_gcount_w212), 
        .AD0(wptr_12), .DO0(af_clr_cmp_set));

    defparam LUT4_1.initval =  16'h8001 ;
    ROM16X1A LUT4_1 (.AD3(af_clrcount_12), .AD2(wcount_12), .AD1(r_gcount_w212), 
        .AD0(wptr_12), .DO0(af_clr_cmp_clr));

    defparam LUT4_0.initval =  16'h4450 ;
    ROM16X1A LUT4_0 (.AD3(af), .AD2(af_set), .AD1(af_clr), .AD0(scuba_vlo), 
        .DO0(af_d));

    defparam pdp_ram_0_0_1.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_0_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_0_1.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_0_1.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_0_1.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_0_1.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_0_1.GSR = "ENABLED" ;
    defparam pdp_ram_0_0_1.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_0_1.REGMODE_B = "NOREG" ;
    defparam pdp_ram_0_0_1.REGMODE_A = "NOREG" ;
    defparam pdp_ram_0_0_1.DATA_WIDTH_B = 4 ;
    defparam pdp_ram_0_0_1.DATA_WIDTH_A = 4 ;
    DP16KD pdp_ram_0_0_1 (.DIA17(scuba_vlo), .DIA16(scuba_vlo), .DIA15(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA13(scuba_vlo), .DIA12(scuba_vlo), .DIA11(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA9(scuba_vlo), .DIA8(scuba_vlo), .DIA7(scuba_vlo), 
        .DIA6(scuba_vlo), .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(Data[3]), 
        .DIA2(Data[2]), .DIA1(Data[1]), .DIA0(Data[0]), .ADA13(wptr_11), 
        .ADA12(wptr_10), .ADA11(wptr_9), .ADA10(wptr_8), .ADA9(wptr_7), 
        .ADA8(wptr_6), .ADA7(wptr_5), .ADA6(wptr_4), .ADA5(wptr_3), .ADA4(wptr_2), 
        .ADA3(wptr_1), .ADA2(wptr_0), .ADA1(scuba_vlo), .ADA0(scuba_vlo), 
        .CEA(wren_i), .OCEA(wren_i), .CLKA(WrClock), .WEA(scuba_vhi), .CSA2(scuba_vlo), 
        .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), .DIB17(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB0(scuba_vlo), .ADB13(rptr_11), .ADB12(rptr_10), .ADB11(rptr_9), 
        .ADB10(rptr_8), .ADB9(rptr_7), .ADB8(rptr_6), .ADB7(rptr_5), .ADB6(rptr_4), 
        .ADB5(rptr_3), .ADB4(rptr_2), .ADB3(rptr_1), .ADB2(rptr_0), .ADB1(scuba_vlo), 
        .ADB0(scuba_vlo), .CEB(rden_i), .OCEB(rden_i), .CLKB(RdClock), .WEB(scuba_vlo), 
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), 
        .DOA17(), .DOA16(), .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), 
        .DOA10(), .DOA9(), .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), 
        .DOA3(), .DOA2(), .DOA1(), .DOA0(), .DOB17(), .DOB16(), .DOB15(), 
        .DOB14(), .DOB13(), .DOB12(), .DOB11(), .DOB10(), .DOB9(), .DOB8(), 
        .DOB7(), .DOB6(), .DOB5(), .DOB4(), .DOB3(Q[3]), .DOB2(Q[2]), .DOB1(Q[1]), 
        .DOB0(Q[0]))
             /* synthesis MEM_LPC_FILE="fifo_8bit_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_1_0.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_1_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_1_0.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_1_0.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_1_0.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_1_0.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_1_0.GSR = "ENABLED" ;
    defparam pdp_ram_0_1_0.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_1_0.REGMODE_B = "NOREG" ;
    defparam pdp_ram_0_1_0.REGMODE_A = "NOREG" ;
    defparam pdp_ram_0_1_0.DATA_WIDTH_B = 4 ;
    defparam pdp_ram_0_1_0.DATA_WIDTH_A = 4 ;
    DP16KD pdp_ram_0_1_0 (.DIA17(scuba_vlo), .DIA16(scuba_vlo), .DIA15(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA13(scuba_vlo), .DIA12(scuba_vlo), .DIA11(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA9(scuba_vlo), .DIA8(scuba_vlo), .DIA7(scuba_vlo), 
        .DIA6(scuba_vlo), .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(Data[7]), 
        .DIA2(Data[6]), .DIA1(Data[5]), .DIA0(Data[4]), .ADA13(wptr_11), 
        .ADA12(wptr_10), .ADA11(wptr_9), .ADA10(wptr_8), .ADA9(wptr_7), 
        .ADA8(wptr_6), .ADA7(wptr_5), .ADA6(wptr_4), .ADA5(wptr_3), .ADA4(wptr_2), 
        .ADA3(wptr_1), .ADA2(wptr_0), .ADA1(scuba_vlo), .ADA0(scuba_vlo), 
        .CEA(wren_i), .OCEA(wren_i), .CLKA(WrClock), .WEA(scuba_vhi), .CSA2(scuba_vlo), 
        .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), .DIB17(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB0(scuba_vlo), .ADB13(rptr_11), .ADB12(rptr_10), .ADB11(rptr_9), 
        .ADB10(rptr_8), .ADB9(rptr_7), .ADB8(rptr_6), .ADB7(rptr_5), .ADB6(rptr_4), 
        .ADB5(rptr_3), .ADB4(rptr_2), .ADB3(rptr_1), .ADB2(rptr_0), .ADB1(scuba_vlo), 
        .ADB0(scuba_vlo), .CEB(rden_i), .OCEB(rden_i), .CLKB(RdClock), .WEB(scuba_vlo), 
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), 
        .DOA17(), .DOA16(), .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), 
        .DOA10(), .DOA9(), .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), 
        .DOA3(), .DOA2(), .DOA1(), .DOA0(), .DOB17(), .DOB16(), .DOB15(), 
        .DOB14(), .DOB13(), .DOB12(), .DOB11(), .DOB10(), .DOB9(), .DOB8(), 
        .DOB7(), .DOB6(), .DOB5(), .DOB4(), .DOB3(Q[7]), .DOB2(Q[6]), .DOB1(Q[5]), 
        .DOB0(Q[4]))
             /* synthesis MEM_LPC_FILE="fifo_8bit_buffer.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3BX FF_158 (.D(iwcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_157 (.D(iwcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_156 (.D(iwcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_155 (.D(iwcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_154 (.D(iwcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_153 (.D(iwcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_152 (.D(iwcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_151 (.D(iwcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_150 (.D(iwcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_149 (.D(iwcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_148 (.D(iwcount_10), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_147 (.D(iwcount_11), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_146 (.D(iwcount_12), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_145 (.D(w_gdata_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_144 (.D(w_gdata_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_143 (.D(w_gdata_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_142 (.D(w_gdata_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_141 (.D(w_gdata_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_140 (.D(w_gdata_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_139 (.D(w_gdata_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_138 (.D(w_gdata_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_137 (.D(w_gdata_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_136 (.D(w_gdata_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_135 (.D(w_gdata_10), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_134 (.D(w_gdata_11), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_133 (.D(wcount_12), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_132 (.D(wcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_131 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_130 (.D(wcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_129 (.D(wcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_128 (.D(wcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_127 (.D(wcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_126 (.D(wcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_125 (.D(wcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_124 (.D(wcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_123 (.D(wcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_122 (.D(wcount_10), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_121 (.D(wcount_11), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_120 (.D(wcount_12), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_119 (.D(ircount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_118 (.D(ircount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_117 (.D(ircount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_116 (.D(ircount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_115 (.D(ircount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_114 (.D(ircount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_113 (.D(ircount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_112 (.D(ircount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_111 (.D(ircount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_110 (.D(ircount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_109 (.D(ircount_10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_108 (.D(ircount_11), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_107 (.D(ircount_12), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_106 (.D(r_gdata_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_105 (.D(r_gdata_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_104 (.D(r_gdata_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_103 (.D(r_gdata_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_102 (.D(r_gdata_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_101 (.D(r_gdata_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_100 (.D(r_gdata_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_99 (.D(r_gdata_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_98 (.D(r_gdata_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_97 (.D(r_gdata_9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_96 (.D(r_gdata_10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_95 (.D(r_gdata_11), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_94 (.D(rcount_12), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_93 (.D(rcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_92 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_91 (.D(rcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_90 (.D(rcount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_89 (.D(rcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_88 (.D(rcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_87 (.D(rcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_86 (.D(rcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_85 (.D(rcount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_84 (.D(rcount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_83 (.D(rcount_10), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_82 (.D(rcount_11), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_81 (.D(rcount_12), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rptr_12))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_80 (.D(w_gcount_0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_79 (.D(w_gcount_1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_78 (.D(w_gcount_2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_77 (.D(w_gcount_3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_76 (.D(w_gcount_4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_75 (.D(w_gcount_5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_74 (.D(w_gcount_6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_73 (.D(w_gcount_7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_72 (.D(w_gcount_8), .CK(RdClock), .CD(Reset), .Q(w_gcount_r8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_71 (.D(w_gcount_9), .CK(RdClock), .CD(Reset), .Q(w_gcount_r9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_70 (.D(w_gcount_10), .CK(RdClock), .CD(Reset), .Q(w_gcount_r10))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_69 (.D(w_gcount_11), .CK(RdClock), .CD(Reset), .Q(w_gcount_r11))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_68 (.D(w_gcount_12), .CK(RdClock), .CD(Reset), .Q(w_gcount_r12))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_67 (.D(r_gcount_0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_66 (.D(r_gcount_1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_65 (.D(r_gcount_2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_64 (.D(r_gcount_3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_63 (.D(r_gcount_4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_62 (.D(r_gcount_5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_61 (.D(r_gcount_6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_60 (.D(r_gcount_7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_59 (.D(r_gcount_8), .CK(WrClock), .CD(rRst), .Q(r_gcount_w8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_58 (.D(r_gcount_9), .CK(WrClock), .CD(rRst), .Q(r_gcount_w9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_57 (.D(r_gcount_10), .CK(WrClock), .CD(rRst), .Q(r_gcount_w10))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_56 (.D(r_gcount_11), .CK(WrClock), .CD(rRst), .Q(r_gcount_w11))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_55 (.D(r_gcount_12), .CK(WrClock), .CD(rRst), .Q(r_gcount_w12))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_54 (.D(w_gcount_r0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_53 (.D(w_gcount_r1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_52 (.D(w_gcount_r2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_51 (.D(w_gcount_r3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_50 (.D(w_gcount_r4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_49 (.D(w_gcount_r5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_48 (.D(w_gcount_r6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_47 (.D(w_gcount_r7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r27))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_46 (.D(w_gcount_r8), .CK(RdClock), .CD(Reset), .Q(w_gcount_r28))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_45 (.D(w_gcount_r9), .CK(RdClock), .CD(Reset), .Q(w_gcount_r29))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_44 (.D(w_gcount_r10), .CK(RdClock), .CD(Reset), .Q(w_gcount_r210))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_43 (.D(w_gcount_r11), .CK(RdClock), .CD(Reset), .Q(w_gcount_r211))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_42 (.D(w_gcount_r12), .CK(RdClock), .CD(Reset), .Q(w_gcount_r212))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_41 (.D(r_gcount_w0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_40 (.D(r_gcount_w1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_39 (.D(r_gcount_w2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_38 (.D(r_gcount_w3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_37 (.D(r_gcount_w4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_36 (.D(r_gcount_w5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_35 (.D(r_gcount_w6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_34 (.D(r_gcount_w7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w27))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_33 (.D(r_gcount_w8), .CK(WrClock), .CD(rRst), .Q(r_gcount_w28))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_32 (.D(r_gcount_w9), .CK(WrClock), .CD(rRst), .Q(r_gcount_w29))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_31 (.D(r_gcount_w10), .CK(WrClock), .CD(rRst), .Q(r_gcount_w210))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_30 (.D(r_gcount_w11), .CK(WrClock), .CD(rRst), .Q(r_gcount_w211))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_29 (.D(r_gcount_w12), .CK(WrClock), .CD(rRst), .Q(r_gcount_w212))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_28 (.D(empty_d), .CK(RdClock), .PD(rRst), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_27 (.D(full_d), .CK(WrClock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_26 (.D(iaf_setcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_setcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(iaf_setcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(iaf_setcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(iaf_setcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(iaf_setcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(iaf_setcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(iaf_setcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(iaf_setcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(iaf_setcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(iaf_setcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(iaf_setcount_10), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_15 (.D(iaf_setcount_11), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_setcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(iaf_setcount_12), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_13 (.D(iaf_clrcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_clrcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(iaf_clrcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_clrcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(iaf_clrcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_clrcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(iaf_clrcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_clrcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_9 (.D(iaf_clrcount_4), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_clrcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_8 (.D(iaf_clrcount_5), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_clrcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(iaf_clrcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_clrcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(iaf_clrcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_clrcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(iaf_clrcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_clrcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(iaf_clrcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_clrcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(iaf_clrcount_10), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_clrcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_2 (.D(iaf_clrcount_11), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_clrcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(iaf_clrcount_12), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_clrcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_0 (.D(af_d), .CK(WrClock), .CD(Reset), .Q(af))
             /* synthesis GSR="ENABLED" */;

    defparam w_gctr_cia.INJECT1_1 = "NO" ;
    defparam w_gctr_cia.INJECT1_0 = "NO" ;
    defparam w_gctr_cia.INIT1 =  16'h66AA ;
    defparam w_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C w_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(w_gctr_ci));

    defparam w_gctr_0.INJECT1_1 = "NO" ;
    defparam w_gctr_0.INJECT1_0 = "NO" ;
    defparam w_gctr_0.INIT1 =  16'h66AA ;
    defparam w_gctr_0.INIT0 =  16'h66AA ;
    CCU2C w_gctr_0 (.A0(wcount_0), .A1(wcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(w_gctr_ci), .S0(iwcount_0), .S1(iwcount_1), .COUT(co0));

    defparam w_gctr_1.INJECT1_1 = "NO" ;
    defparam w_gctr_1.INJECT1_0 = "NO" ;
    defparam w_gctr_1.INIT1 =  16'h66AA ;
    defparam w_gctr_1.INIT0 =  16'h66AA ;
    CCU2C w_gctr_1 (.A0(wcount_2), .A1(wcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0), .S0(iwcount_2), .S1(iwcount_3), .COUT(co1));

    defparam w_gctr_2.INJECT1_1 = "NO" ;
    defparam w_gctr_2.INJECT1_0 = "NO" ;
    defparam w_gctr_2.INIT1 =  16'h66AA ;
    defparam w_gctr_2.INIT0 =  16'h66AA ;
    CCU2C w_gctr_2 (.A0(wcount_4), .A1(wcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1), .S0(iwcount_4), .S1(iwcount_5), .COUT(co2));

    defparam w_gctr_3.INJECT1_1 = "NO" ;
    defparam w_gctr_3.INJECT1_0 = "NO" ;
    defparam w_gctr_3.INIT1 =  16'h66AA ;
    defparam w_gctr_3.INIT0 =  16'h66AA ;
    CCU2C w_gctr_3 (.A0(wcount_6), .A1(wcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2), .S0(iwcount_6), .S1(iwcount_7), .COUT(co3));

    defparam w_gctr_4.INJECT1_1 = "NO" ;
    defparam w_gctr_4.INJECT1_0 = "NO" ;
    defparam w_gctr_4.INIT1 =  16'h66AA ;
    defparam w_gctr_4.INIT0 =  16'h66AA ;
    CCU2C w_gctr_4 (.A0(wcount_8), .A1(wcount_9), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3), .S0(iwcount_8), .S1(iwcount_9), .COUT(co4));

    defparam w_gctr_5.INJECT1_1 = "NO" ;
    defparam w_gctr_5.INJECT1_0 = "NO" ;
    defparam w_gctr_5.INIT1 =  16'h66AA ;
    defparam w_gctr_5.INIT0 =  16'h66AA ;
    CCU2C w_gctr_5 (.A0(wcount_10), .A1(wcount_11), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4), .S0(iwcount_10), .S1(iwcount_11), .COUT(co5));

    defparam w_gctr_6.INJECT1_1 = "NO" ;
    defparam w_gctr_6.INJECT1_0 = "NO" ;
    defparam w_gctr_6.INIT1 =  16'h66AA ;
    defparam w_gctr_6.INIT0 =  16'h66AA ;
    CCU2C w_gctr_6 (.A0(wcount_12), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co5), .S0(iwcount_12), .S1(), .COUT(co6));

    defparam r_gctr_cia.INJECT1_1 = "NO" ;
    defparam r_gctr_cia.INJECT1_0 = "NO" ;
    defparam r_gctr_cia.INIT1 =  16'h66AA ;
    defparam r_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C r_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(r_gctr_ci));

    defparam r_gctr_0.INJECT1_1 = "NO" ;
    defparam r_gctr_0.INJECT1_0 = "NO" ;
    defparam r_gctr_0.INIT1 =  16'h66AA ;
    defparam r_gctr_0.INIT0 =  16'h66AA ;
    CCU2C r_gctr_0 (.A0(rcount_0), .A1(rcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(r_gctr_ci), .S0(ircount_0), .S1(ircount_1), .COUT(co0_1));

    defparam r_gctr_1.INJECT1_1 = "NO" ;
    defparam r_gctr_1.INJECT1_0 = "NO" ;
    defparam r_gctr_1.INIT1 =  16'h66AA ;
    defparam r_gctr_1.INIT0 =  16'h66AA ;
    CCU2C r_gctr_1 (.A0(rcount_2), .A1(rcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_1), .S0(ircount_2), .S1(ircount_3), .COUT(co1_1));

    defparam r_gctr_2.INJECT1_1 = "NO" ;
    defparam r_gctr_2.INJECT1_0 = "NO" ;
    defparam r_gctr_2.INIT1 =  16'h66AA ;
    defparam r_gctr_2.INIT0 =  16'h66AA ;
    CCU2C r_gctr_2 (.A0(rcount_4), .A1(rcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_1), .S0(ircount_4), .S1(ircount_5), .COUT(co2_1));

    defparam r_gctr_3.INJECT1_1 = "NO" ;
    defparam r_gctr_3.INJECT1_0 = "NO" ;
    defparam r_gctr_3.INIT1 =  16'h66AA ;
    defparam r_gctr_3.INIT0 =  16'h66AA ;
    CCU2C r_gctr_3 (.A0(rcount_6), .A1(rcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_1), .S0(ircount_6), .S1(ircount_7), .COUT(co3_1));

    defparam r_gctr_4.INJECT1_1 = "NO" ;
    defparam r_gctr_4.INJECT1_0 = "NO" ;
    defparam r_gctr_4.INIT1 =  16'h66AA ;
    defparam r_gctr_4.INIT0 =  16'h66AA ;
    CCU2C r_gctr_4 (.A0(rcount_8), .A1(rcount_9), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_1), .S0(ircount_8), .S1(ircount_9), .COUT(co4_1));

    defparam r_gctr_5.INJECT1_1 = "NO" ;
    defparam r_gctr_5.INJECT1_0 = "NO" ;
    defparam r_gctr_5.INIT1 =  16'h66AA ;
    defparam r_gctr_5.INIT0 =  16'h66AA ;
    CCU2C r_gctr_5 (.A0(rcount_10), .A1(rcount_11), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4_1), .S0(ircount_10), .S1(ircount_11), .COUT(co5_1));

    defparam r_gctr_6.INJECT1_1 = "NO" ;
    defparam r_gctr_6.INJECT1_0 = "NO" ;
    defparam r_gctr_6.INIT1 =  16'h66AA ;
    defparam r_gctr_6.INIT0 =  16'h66AA ;
    CCU2C r_gctr_6 (.A0(rcount_12), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co5_1), .S0(ircount_12), .S1(), .COUT(co6_1));

    defparam empty_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam empty_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam empty_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam empty_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C empty_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), .B1(rden_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci));

    defparam empty_cmp_0.INJECT1_1 = "NO" ;
    defparam empty_cmp_0.INJECT1_0 = "NO" ;
    defparam empty_cmp_0.INIT1 =  16'h99AA ;
    defparam empty_cmp_0.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_0 (.A0(rcount_0), .A1(rcount_1), .B0(wcount_r0), .B1(wcount_r1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci), .S0(), .S1(), .COUT(co0_2));

    defparam empty_cmp_1.INJECT1_1 = "NO" ;
    defparam empty_cmp_1.INJECT1_0 = "NO" ;
    defparam empty_cmp_1.INIT1 =  16'h99AA ;
    defparam empty_cmp_1.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_1 (.A0(rcount_2), .A1(rcount_3), .B0(wcount_r2), .B1(wcount_r3), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_2), .S0(), .S1(), .COUT(co1_2));

    defparam empty_cmp_2.INJECT1_1 = "NO" ;
    defparam empty_cmp_2.INJECT1_0 = "NO" ;
    defparam empty_cmp_2.INIT1 =  16'h99AA ;
    defparam empty_cmp_2.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_2 (.A0(rcount_4), .A1(rcount_5), .B0(wcount_r4), .B1(wcount_r5), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_2), .S0(), .S1(), .COUT(co2_2));

    defparam empty_cmp_3.INJECT1_1 = "NO" ;
    defparam empty_cmp_3.INJECT1_0 = "NO" ;
    defparam empty_cmp_3.INIT1 =  16'h99AA ;
    defparam empty_cmp_3.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_3 (.A0(rcount_6), .A1(rcount_7), .B0(wcount_r6), .B1(wcount_r7), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_2), .S0(), .S1(), .COUT(co3_2));

    defparam empty_cmp_4.INJECT1_1 = "NO" ;
    defparam empty_cmp_4.INJECT1_0 = "NO" ;
    defparam empty_cmp_4.INIT1 =  16'h99AA ;
    defparam empty_cmp_4.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_4 (.A0(rcount_8), .A1(rcount_9), .B0(wcount_r8), .B1(w_g2b_xor_cluster_0), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_2), .S0(), .S1(), .COUT(co4_2));

    defparam empty_cmp_5.INJECT1_1 = "NO" ;
    defparam empty_cmp_5.INJECT1_0 = "NO" ;
    defparam empty_cmp_5.INIT1 =  16'h99AA ;
    defparam empty_cmp_5.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_5 (.A0(rcount_10), .A1(rcount_11), .B0(wcount_r10), 
        .B1(wcount_r11), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co4_2), .S0(), .S1(), .COUT(co5_2));

    defparam empty_cmp_6.INJECT1_1 = "NO" ;
    defparam empty_cmp_6.INJECT1_0 = "NO" ;
    defparam empty_cmp_6.INIT1 =  16'h99AA ;
    defparam empty_cmp_6.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_6 (.A0(empty_cmp_set), .A1(scuba_vlo), .B0(empty_cmp_clr), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co5_2), .S0(), .S1(), .COUT(empty_d_c));

    defparam a0.INJECT1_1 = "NO" ;
    defparam a0.INJECT1_0 = "NO" ;
    defparam a0.INIT1 =  16'h66AA ;
    defparam a0.INIT0 =  16'h66AA ;
    CCU2C a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(empty_d_c), .S0(empty_d), .S1(), .COUT());

    defparam full_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam full_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam full_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam full_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C full_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_1));

    defparam full_cmp_0.INJECT1_1 = "NO" ;
    defparam full_cmp_0.INJECT1_0 = "NO" ;
    defparam full_cmp_0.INIT1 =  16'h99AA ;
    defparam full_cmp_0.INIT0 =  16'h99AA ;
    CCU2C full_cmp_0 (.A0(wcount_0), .A1(wcount_1), .B0(rcount_w0), .B1(rcount_w1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci_1), .S0(), .S1(), .COUT(co0_3));

    defparam full_cmp_1.INJECT1_1 = "NO" ;
    defparam full_cmp_1.INJECT1_0 = "NO" ;
    defparam full_cmp_1.INIT1 =  16'h99AA ;
    defparam full_cmp_1.INIT0 =  16'h99AA ;
    CCU2C full_cmp_1 (.A0(wcount_2), .A1(wcount_3), .B0(rcount_w2), .B1(rcount_w3), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_3), .S0(), .S1(), .COUT(co1_3));

    defparam full_cmp_2.INJECT1_1 = "NO" ;
    defparam full_cmp_2.INJECT1_0 = "NO" ;
    defparam full_cmp_2.INIT1 =  16'h99AA ;
    defparam full_cmp_2.INIT0 =  16'h99AA ;
    CCU2C full_cmp_2 (.A0(wcount_4), .A1(wcount_5), .B0(rcount_w4), .B1(rcount_w5), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_3), .S0(), .S1(), .COUT(co2_3));

    defparam full_cmp_3.INJECT1_1 = "NO" ;
    defparam full_cmp_3.INJECT1_0 = "NO" ;
    defparam full_cmp_3.INIT1 =  16'h99AA ;
    defparam full_cmp_3.INIT0 =  16'h99AA ;
    CCU2C full_cmp_3 (.A0(wcount_6), .A1(wcount_7), .B0(rcount_w6), .B1(rcount_w7), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_3), .S0(), .S1(), .COUT(co3_3));

    defparam full_cmp_4.INJECT1_1 = "NO" ;
    defparam full_cmp_4.INJECT1_0 = "NO" ;
    defparam full_cmp_4.INIT1 =  16'h99AA ;
    defparam full_cmp_4.INIT0 =  16'h99AA ;
    CCU2C full_cmp_4 (.A0(wcount_8), .A1(wcount_9), .B0(rcount_w8), .B1(r_g2b_xor_cluster_0), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_3), .S0(), .S1(), .COUT(co4_3));

    defparam full_cmp_5.INJECT1_1 = "NO" ;
    defparam full_cmp_5.INJECT1_0 = "NO" ;
    defparam full_cmp_5.INIT1 =  16'h99AA ;
    defparam full_cmp_5.INIT0 =  16'h99AA ;
    CCU2C full_cmp_5 (.A0(wcount_10), .A1(wcount_11), .B0(rcount_w10), .B1(rcount_w11), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4_3), .S0(), .S1(), .COUT(co5_3));

    defparam full_cmp_6.INJECT1_1 = "NO" ;
    defparam full_cmp_6.INJECT1_0 = "NO" ;
    defparam full_cmp_6.INIT1 =  16'h99AA ;
    defparam full_cmp_6.INIT0 =  16'h99AA ;
    CCU2C full_cmp_6 (.A0(full_cmp_set), .A1(scuba_vlo), .B0(full_cmp_clr), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co5_3), .S0(), .S1(), .COUT(full_d_c));

    defparam a1.INJECT1_1 = "NO" ;
    defparam a1.INJECT1_0 = "NO" ;
    defparam a1.INIT1 =  16'h66AA ;
    defparam a1.INIT0 =  16'h66AA ;
    CCU2C a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(full_d_c), .S0(full_d), .S1(), .COUT());

    defparam af_set_ctr_cia.INJECT1_1 = "NO" ;
    defparam af_set_ctr_cia.INJECT1_0 = "NO" ;
    defparam af_set_ctr_cia.INIT1 =  16'h66AA ;
    defparam af_set_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(af_set_ctr_ci));

    defparam af_set_ctr_0.INJECT1_1 = "NO" ;
    defparam af_set_ctr_0.INJECT1_0 = "NO" ;
    defparam af_set_ctr_0.INIT1 =  16'h66AA ;
    defparam af_set_ctr_0.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_0 (.A0(af_setcount_0), .A1(af_setcount_1), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(af_set_ctr_ci), .S0(iaf_setcount_0), .S1(iaf_setcount_1), 
        .COUT(co0_4));

    defparam af_set_ctr_1.INJECT1_1 = "NO" ;
    defparam af_set_ctr_1.INJECT1_0 = "NO" ;
    defparam af_set_ctr_1.INIT1 =  16'h66AA ;
    defparam af_set_ctr_1.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_1 (.A0(af_setcount_2), .A1(af_setcount_3), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_4), .S0(iaf_setcount_2), .S1(iaf_setcount_3), 
        .COUT(co1_4));

    defparam af_set_ctr_2.INJECT1_1 = "NO" ;
    defparam af_set_ctr_2.INJECT1_0 = "NO" ;
    defparam af_set_ctr_2.INIT1 =  16'h66AA ;
    defparam af_set_ctr_2.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_2 (.A0(af_setcount_4), .A1(af_setcount_5), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_4), .S0(iaf_setcount_4), .S1(iaf_setcount_5), 
        .COUT(co2_4));

    defparam af_set_ctr_3.INJECT1_1 = "NO" ;
    defparam af_set_ctr_3.INJECT1_0 = "NO" ;
    defparam af_set_ctr_3.INIT1 =  16'h66AA ;
    defparam af_set_ctr_3.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_3 (.A0(af_setcount_6), .A1(af_setcount_7), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_4), .S0(iaf_setcount_6), .S1(iaf_setcount_7), 
        .COUT(co3_4));

    defparam af_set_ctr_4.INJECT1_1 = "NO" ;
    defparam af_set_ctr_4.INJECT1_0 = "NO" ;
    defparam af_set_ctr_4.INIT1 =  16'h66AA ;
    defparam af_set_ctr_4.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_4 (.A0(af_setcount_8), .A1(af_setcount_9), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_4), .S0(iaf_setcount_8), .S1(iaf_setcount_9), 
        .COUT(co4_4));

    defparam af_set_ctr_5.INJECT1_1 = "NO" ;
    defparam af_set_ctr_5.INJECT1_0 = "NO" ;
    defparam af_set_ctr_5.INIT1 =  16'h66AA ;
    defparam af_set_ctr_5.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_5 (.A0(af_setcount_10), .A1(af_setcount_11), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co4_4), .S0(iaf_setcount_10), .S1(iaf_setcount_11), 
        .COUT(co5_4));

    defparam af_set_ctr_6.INJECT1_1 = "NO" ;
    defparam af_set_ctr_6.INJECT1_0 = "NO" ;
    defparam af_set_ctr_6.INIT1 =  16'h66AA ;
    defparam af_set_ctr_6.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_6 (.A0(af_setcount_12), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co5_4), .S0(iaf_setcount_12), .S1(), .COUT(co6_2));

    defparam af_set_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam af_set_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam af_set_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam af_set_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C af_set_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), 
        .B1(wren_i), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_2));

    defparam af_set_cmp_0.INJECT1_1 = "NO" ;
    defparam af_set_cmp_0.INJECT1_0 = "NO" ;
    defparam af_set_cmp_0.INIT1 =  16'h99AA ;
    defparam af_set_cmp_0.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_0 (.A0(af_setcount_0), .A1(af_setcount_1), .B0(rcount_w0), 
        .B1(rcount_w1), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(cmp_ci_2), .S0(), .S1(), .COUT(co0_5));

    defparam af_set_cmp_1.INJECT1_1 = "NO" ;
    defparam af_set_cmp_1.INJECT1_0 = "NO" ;
    defparam af_set_cmp_1.INIT1 =  16'h99AA ;
    defparam af_set_cmp_1.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_1 (.A0(af_setcount_2), .A1(af_setcount_3), .B0(rcount_w2), 
        .B1(rcount_w3), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_5), .S0(), .S1(), .COUT(co1_5));

    defparam af_set_cmp_2.INJECT1_1 = "NO" ;
    defparam af_set_cmp_2.INJECT1_0 = "NO" ;
    defparam af_set_cmp_2.INIT1 =  16'h99AA ;
    defparam af_set_cmp_2.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_2 (.A0(af_setcount_4), .A1(af_setcount_5), .B0(rcount_w4), 
        .B1(rcount_w5), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_5), .S0(), .S1(), .COUT(co2_5));

    defparam af_set_cmp_3.INJECT1_1 = "NO" ;
    defparam af_set_cmp_3.INJECT1_0 = "NO" ;
    defparam af_set_cmp_3.INIT1 =  16'h99AA ;
    defparam af_set_cmp_3.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_3 (.A0(af_setcount_6), .A1(af_setcount_7), .B0(rcount_w6), 
        .B1(rcount_w7), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_5), .S0(), .S1(), .COUT(co3_5));

    defparam af_set_cmp_4.INJECT1_1 = "NO" ;
    defparam af_set_cmp_4.INJECT1_0 = "NO" ;
    defparam af_set_cmp_4.INIT1 =  16'h99AA ;
    defparam af_set_cmp_4.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_4 (.A0(af_setcount_8), .A1(af_setcount_9), .B0(rcount_w8), 
        .B1(r_g2b_xor_cluster_0), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_5), .S0(), .S1(), .COUT(co4_5));

    defparam af_set_cmp_5.INJECT1_1 = "NO" ;
    defparam af_set_cmp_5.INJECT1_0 = "NO" ;
    defparam af_set_cmp_5.INIT1 =  16'h99AA ;
    defparam af_set_cmp_5.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_5 (.A0(af_setcount_10), .A1(af_setcount_11), .B0(rcount_w10), 
        .B1(rcount_w11), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co4_5), .S0(), .S1(), .COUT(co5_5));

    defparam af_set_cmp_6.INJECT1_1 = "NO" ;
    defparam af_set_cmp_6.INJECT1_0 = "NO" ;
    defparam af_set_cmp_6.INIT1 =  16'h99AA ;
    defparam af_set_cmp_6.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_6 (.A0(af_set_cmp_set), .A1(scuba_vlo), .B0(af_set_cmp_clr), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co5_5), .S0(), .S1(), .COUT(af_set_c));

    defparam a2.INJECT1_1 = "NO" ;
    defparam a2.INJECT1_0 = "NO" ;
    defparam a2.INIT1 =  16'h66AA ;
    defparam a2.INIT0 =  16'h66AA ;
    CCU2C a2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(af_set_c), .S0(af_set), .S1(), .COUT());

    defparam af_clr_ctr_cia.INJECT1_1 = "NO" ;
    defparam af_clr_ctr_cia.INJECT1_0 = "NO" ;
    defparam af_clr_ctr_cia.INIT1 =  16'h66AA ;
    defparam af_clr_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C af_clr_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(af_clr_ctr_ci));

    defparam af_clr_ctr_0.INJECT1_1 = "NO" ;
    defparam af_clr_ctr_0.INJECT1_0 = "NO" ;
    defparam af_clr_ctr_0.INIT1 =  16'h66AA ;
    defparam af_clr_ctr_0.INIT0 =  16'h66AA ;
    CCU2C af_clr_ctr_0 (.A0(af_clrcount_0), .A1(af_clrcount_1), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(af_clr_ctr_ci), .S0(iaf_clrcount_0), .S1(iaf_clrcount_1), 
        .COUT(co0_6));

    defparam af_clr_ctr_1.INJECT1_1 = "NO" ;
    defparam af_clr_ctr_1.INJECT1_0 = "NO" ;
    defparam af_clr_ctr_1.INIT1 =  16'h66AA ;
    defparam af_clr_ctr_1.INIT0 =  16'h66AA ;
    CCU2C af_clr_ctr_1 (.A0(af_clrcount_2), .A1(af_clrcount_3), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_6), .S0(iaf_clrcount_2), .S1(iaf_clrcount_3), 
        .COUT(co1_6));

    defparam af_clr_ctr_2.INJECT1_1 = "NO" ;
    defparam af_clr_ctr_2.INJECT1_0 = "NO" ;
    defparam af_clr_ctr_2.INIT1 =  16'h66AA ;
    defparam af_clr_ctr_2.INIT0 =  16'h66AA ;
    CCU2C af_clr_ctr_2 (.A0(af_clrcount_4), .A1(af_clrcount_5), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_6), .S0(iaf_clrcount_4), .S1(iaf_clrcount_5), 
        .COUT(co2_6));

    defparam af_clr_ctr_3.INJECT1_1 = "NO" ;
    defparam af_clr_ctr_3.INJECT1_0 = "NO" ;
    defparam af_clr_ctr_3.INIT1 =  16'h66AA ;
    defparam af_clr_ctr_3.INIT0 =  16'h66AA ;
    CCU2C af_clr_ctr_3 (.A0(af_clrcount_6), .A1(af_clrcount_7), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_6), .S0(iaf_clrcount_6), .S1(iaf_clrcount_7), 
        .COUT(co3_6));

    defparam af_clr_ctr_4.INJECT1_1 = "NO" ;
    defparam af_clr_ctr_4.INJECT1_0 = "NO" ;
    defparam af_clr_ctr_4.INIT1 =  16'h66AA ;
    defparam af_clr_ctr_4.INIT0 =  16'h66AA ;
    CCU2C af_clr_ctr_4 (.A0(af_clrcount_8), .A1(af_clrcount_9), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_6), .S0(iaf_clrcount_8), .S1(iaf_clrcount_9), 
        .COUT(co4_6));

    defparam af_clr_ctr_5.INJECT1_1 = "NO" ;
    defparam af_clr_ctr_5.INJECT1_0 = "NO" ;
    defparam af_clr_ctr_5.INIT1 =  16'h66AA ;
    defparam af_clr_ctr_5.INIT0 =  16'h66AA ;
    CCU2C af_clr_ctr_5 (.A0(af_clrcount_10), .A1(af_clrcount_11), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co4_6), .S0(iaf_clrcount_10), .S1(iaf_clrcount_11), 
        .COUT(co5_6));

    defparam af_clr_ctr_6.INJECT1_1 = "NO" ;
    defparam af_clr_ctr_6.INJECT1_0 = "NO" ;
    defparam af_clr_ctr_6.INIT1 =  16'h66AA ;
    defparam af_clr_ctr_6.INIT0 =  16'h66AA ;
    CCU2C af_clr_ctr_6 (.A0(af_clrcount_12), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co5_6), .S0(iaf_clrcount_12), .S1(), .COUT(co6_3));

    defparam af_clr_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam af_clr_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam af_clr_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam af_clr_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C af_clr_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), 
        .B1(wren_i), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_3));

    defparam af_clr_cmp_0.INJECT1_1 = "NO" ;
    defparam af_clr_cmp_0.INJECT1_0 = "NO" ;
    defparam af_clr_cmp_0.INIT1 =  16'h99AA ;
    defparam af_clr_cmp_0.INIT0 =  16'h99AA ;
    CCU2C af_clr_cmp_0 (.A0(af_clrcount_0), .A1(af_clrcount_1), .B0(rcount_w0), 
        .B1(rcount_w1), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(cmp_ci_3), .S0(), .S1(), .COUT(co0_7));

    defparam af_clr_cmp_1.INJECT1_1 = "NO" ;
    defparam af_clr_cmp_1.INJECT1_0 = "NO" ;
    defparam af_clr_cmp_1.INIT1 =  16'h99AA ;
    defparam af_clr_cmp_1.INIT0 =  16'h99AA ;
    CCU2C af_clr_cmp_1 (.A0(af_clrcount_2), .A1(af_clrcount_3), .B0(rcount_w2), 
        .B1(rcount_w3), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_7), .S0(), .S1(), .COUT(co1_7));

    defparam af_clr_cmp_2.INJECT1_1 = "NO" ;
    defparam af_clr_cmp_2.INJECT1_0 = "NO" ;
    defparam af_clr_cmp_2.INIT1 =  16'h99AA ;
    defparam af_clr_cmp_2.INIT0 =  16'h99AA ;
    CCU2C af_clr_cmp_2 (.A0(af_clrcount_4), .A1(af_clrcount_5), .B0(rcount_w4), 
        .B1(rcount_w5), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_7), .S0(), .S1(), .COUT(co2_7));

    defparam af_clr_cmp_3.INJECT1_1 = "NO" ;
    defparam af_clr_cmp_3.INJECT1_0 = "NO" ;
    defparam af_clr_cmp_3.INIT1 =  16'h99AA ;
    defparam af_clr_cmp_3.INIT0 =  16'h99AA ;
    CCU2C af_clr_cmp_3 (.A0(af_clrcount_6), .A1(af_clrcount_7), .B0(rcount_w6), 
        .B1(rcount_w7), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_7), .S0(), .S1(), .COUT(co3_7));

    defparam af_clr_cmp_4.INJECT1_1 = "NO" ;
    defparam af_clr_cmp_4.INJECT1_0 = "NO" ;
    defparam af_clr_cmp_4.INIT1 =  16'h99AA ;
    defparam af_clr_cmp_4.INIT0 =  16'h99AA ;
    CCU2C af_clr_cmp_4 (.A0(af_clrcount_8), .A1(af_clrcount_9), .B0(rcount_w8), 
        .B1(r_g2b_xor_cluster_0), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_7), .S0(), .S1(), .COUT(co4_7));

    defparam af_clr_cmp_5.INJECT1_1 = "NO" ;
    defparam af_clr_cmp_5.INJECT1_0 = "NO" ;
    defparam af_clr_cmp_5.INIT1 =  16'h99AA ;
    defparam af_clr_cmp_5.INIT0 =  16'h99AA ;
    CCU2C af_clr_cmp_5 (.A0(af_clrcount_10), .A1(af_clrcount_11), .B0(rcount_w10), 
        .B1(rcount_w11), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co4_7), .S0(), .S1(), .COUT(co5_7));

    defparam af_clr_cmp_6.INJECT1_1 = "NO" ;
    defparam af_clr_cmp_6.INJECT1_0 = "NO" ;
    defparam af_clr_cmp_6.INIT1 =  16'h99AA ;
    defparam af_clr_cmp_6.INIT0 =  16'h99AA ;
    CCU2C af_clr_cmp_6 (.A0(af_clr_cmp_set), .A1(scuba_vlo), .B0(af_clr_cmp_clr), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co5_7), .S0(), .S1(), .COUT(af_clr_c));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam a3.INJECT1_1 = "NO" ;
    defparam a3.INJECT1_0 = "NO" ;
    defparam a3.INIT1 =  16'h66AA ;
    defparam a3.INIT0 =  16'h66AA ;
    CCU2C a3 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(af_clr_c), .S0(af_clr), .S1(), .COUT());

    assign Empty = empty_i;
    assign Full = full_i;
    assign AlmostFull = af;


    // exemplar begin
    // exemplar attribute pdp_ram_0_0_1 MEM_LPC_FILE fifo_8bit_buffer.lpc
    // exemplar attribute pdp_ram_0_0_1 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_1_0 MEM_LPC_FILE fifo_8bit_buffer.lpc
    // exemplar attribute pdp_ram_0_1_0 MEM_INIT_FILE 
    // exemplar attribute FF_158 GSR ENABLED
    // exemplar attribute FF_157 GSR ENABLED
    // exemplar attribute FF_156 GSR ENABLED
    // exemplar attribute FF_155 GSR ENABLED
    // exemplar attribute FF_154 GSR ENABLED
    // exemplar attribute FF_153 GSR ENABLED
    // exemplar attribute FF_152 GSR ENABLED
    // exemplar attribute FF_151 GSR ENABLED
    // exemplar attribute FF_150 GSR ENABLED
    // exemplar attribute FF_149 GSR ENABLED
    // exemplar attribute FF_148 GSR ENABLED
    // exemplar attribute FF_147 GSR ENABLED
    // exemplar attribute FF_146 GSR ENABLED
    // exemplar attribute FF_145 GSR ENABLED
    // exemplar attribute FF_144 GSR ENABLED
    // exemplar attribute FF_143 GSR ENABLED
    // exemplar attribute FF_142 GSR ENABLED
    // exemplar attribute FF_141 GSR ENABLED
    // exemplar attribute FF_140 GSR ENABLED
    // exemplar attribute FF_139 GSR ENABLED
    // exemplar attribute FF_138 GSR ENABLED
    // exemplar attribute FF_137 GSR ENABLED
    // exemplar attribute FF_136 GSR ENABLED
    // exemplar attribute FF_135 GSR ENABLED
    // exemplar attribute FF_134 GSR ENABLED
    // exemplar attribute FF_133 GSR ENABLED
    // exemplar attribute FF_132 GSR ENABLED
    // exemplar attribute FF_131 GSR ENABLED
    // exemplar attribute FF_130 GSR ENABLED
    // exemplar attribute FF_129 GSR ENABLED
    // exemplar attribute FF_128 GSR ENABLED
    // exemplar attribute FF_127 GSR ENABLED
    // exemplar attribute FF_126 GSR ENABLED
    // exemplar attribute FF_125 GSR ENABLED
    // exemplar attribute FF_124 GSR ENABLED
    // exemplar attribute FF_123 GSR ENABLED
    // exemplar attribute FF_122 GSR ENABLED
    // exemplar attribute FF_121 GSR ENABLED
    // exemplar attribute FF_120 GSR ENABLED
    // exemplar attribute FF_119 GSR ENABLED
    // exemplar attribute FF_118 GSR ENABLED
    // exemplar attribute FF_117 GSR ENABLED
    // exemplar attribute FF_116 GSR ENABLED
    // exemplar attribute FF_115 GSR ENABLED
    // exemplar attribute FF_114 GSR ENABLED
    // exemplar attribute FF_113 GSR ENABLED
    // exemplar attribute FF_112 GSR ENABLED
    // exemplar attribute FF_111 GSR ENABLED
    // exemplar attribute FF_110 GSR ENABLED
    // exemplar attribute FF_109 GSR ENABLED
    // exemplar attribute FF_108 GSR ENABLED
    // exemplar attribute FF_107 GSR ENABLED
    // exemplar attribute FF_106 GSR ENABLED
    // exemplar attribute FF_105 GSR ENABLED
    // exemplar attribute FF_104 GSR ENABLED
    // exemplar attribute FF_103 GSR ENABLED
    // exemplar attribute FF_102 GSR ENABLED
    // exemplar attribute FF_101 GSR ENABLED
    // exemplar attribute FF_100 GSR ENABLED
    // exemplar attribute FF_99 GSR ENABLED
    // exemplar attribute FF_98 GSR ENABLED
    // exemplar attribute FF_97 GSR ENABLED
    // exemplar attribute FF_96 GSR ENABLED
    // exemplar attribute FF_95 GSR ENABLED
    // exemplar attribute FF_94 GSR ENABLED
    // exemplar attribute FF_93 GSR ENABLED
    // exemplar attribute FF_92 GSR ENABLED
    // exemplar attribute FF_91 GSR ENABLED
    // exemplar attribute FF_90 GSR ENABLED
    // exemplar attribute FF_89 GSR ENABLED
    // exemplar attribute FF_88 GSR ENABLED
    // exemplar attribute FF_87 GSR ENABLED
    // exemplar attribute FF_86 GSR ENABLED
    // exemplar attribute FF_85 GSR ENABLED
    // exemplar attribute FF_84 GSR ENABLED
    // exemplar attribute FF_83 GSR ENABLED
    // exemplar attribute FF_82 GSR ENABLED
    // exemplar attribute FF_81 GSR ENABLED
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
