/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.2.115 */
/* Module Version: 5.8 */
/* Fri Jul 05 18:26:01 2019 */

/* parameterized module instance */
fifo_8bit_sl __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), .AlmostEmpty( ), 
    .AlmostFull( ));
